name: Bicep CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  bicep-deploy:
    runs-on: ubuntu-latest
    env:
      BICEP_FILE: iac-bicep/envs/dev/main.bicep
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}"
            }

      - name: Bicep Lint
        run: az bicep build --file $BICEP_FILE

      - name: Bicep What-If (Preview)
        run: az deployment sub what-if --location eastus --template-file $BICEP_FILE

      - name: Bicep Deploy (manual approval)
        run: az deployment sub create --location eastus --template-file $BICEP_FILE
